project:
  type: site
  title: "friendly-dollop"
  output-dir: _site
  
execute:
  freeze: true
  warning: false

site:
  title: "Quarto + RMD + Github Pages Test"
  sharing: [twitter, facebook, linkedin]
  repo-url: https://github.com/pommevilla/friendly-dollop
  
  navbar:
    background: "dark"
    right:
      - text: "Home"
        file: index.Rmd
      - text: "Basic Stats"
        file: statistics.Rmd
      - text: "Biodiversity"
        file: biodiversity.Rmd
      - text: "Example iPyNb"
        file: sample_python.ipynb
      - text: "GERMS Lab"
        url: http://www.germslab.org/
      - text: "Other stuff"
        menu:
          - text: "My Github"
            url: https://github.com/pommevilla/
          - text: "TFT 3.5: 500 Challenger Matches"
            url: https://www.kaggle.com/pvillanueva13/tft-35-500-gm-matches
          
        
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/pommevilla/friendly-dollop
    contents:
      - index.Rmd
      - statistics.Rmd
      - biodiversity.Rmd
      - sample_python.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true
