name: Render and deploy Quarto files
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - uses: actions/checkout@v2

    - name: "Install quarto bin"
      run: |
        curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | 
        grep "browser_download_url.*deb" | 
        cut -d '"' -f 4 |
        wget -i -

        sudo dpkg -i $(ls quarto*deb)

    - uses: actions/setup-python@v2

    # - name: "Install Python deps"
    #   run: |
    #     if [ -f requirements.txt ]
    #     then
    #       grep -iv "win" requirements.txt > TEMP_requirements.txt
    #       pip install -r TEMP_requirements.txt
    #     else
    #       echo "requirements.txt not found"
    #     fi

    # - name: "Install curl for Bioconductor Installation"
    #   run: |
    #     sudo apt -y install libcurl4-openssl-dev

    # - uses: r-lib/actions/setup-r@v1

    # - name: "Install R Packages: Cache packages"
    #   uses: actions/cache@v1
    #   with:
    #     path: ${{ env.RENV_PATHS_ROOT }}
    #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-renv-

    # - name: "Install R Packages: Restore packages"
    #   shell: Rscript {0}
    #   run: |
    #     if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
    #     renv::restore()

    # - name: "Quarto env"
    #   run: |
    #     quarto env

    # - name: "Quarto capabilities"
    #   run: |
    #     quarto capabilities

    # - name: "Quarto check"
    #   run: |
    #     quarto check

    - name: "Render directory"
      run: |
        quarto render --execute-debug 

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
